FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel

ENV JUPYTER_CONFIG_DIR=/data/jupyter/
COPY requirements.txt ./
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y gcc
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt